apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: interviewai
  labels:
    app: backend
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  type: LoadBalancer    # Exposes backend publicly via AWS NLB
  selector:
    app: backend
  ports:
    - name: http
      port: 80
      targetPort: 5000
      protocol: TCP
