# ============================================================
# Backend Secret — store sensitive env vars in K8s Secrets
# Run: kubectl apply -f k8s/backend-secret.yml -n interviewai
# ============================================================
apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: interviewai
type: Opaque
stringData:
  NODE_ENV: "production"
  PORT: "5000"
  MONGODB_URI: "mongodb://Mayank:Mayankatwal@ac-3wqzttk-shard-00-00.mamw7nb.mongodb.net:27017,ac-3wqzttk-shard-00-01.mamw7nb.mongodb.net:27017,ac-3wqzttk-shard-00-02.mamw7nb.mongodb.net:27017/interview_platform?ssl=true&replicaSet=atlas-u8gklu-shard-0&authSource=admin&retryWrites=true&w=majority"
  JWT_SECRET: "prd-jwt-s3cr3t-interviewa1-p1atform-2024-$ecure!"
  JWT_REFRESH_SECRET: "prd-refresh-s3cr3t-interviewa1-p1atform-2024!"
  JWT_EXPIRES_IN: "7d"
  JWT_REFRESH_EXPIRES_IN: "30d"
  GEMINI_API_KEY: "AIzaSyCIdmJJO85yVg5yETBqckDAz_rtPE-l-uY"
  GEMINI_MODEL: "gemini-2.5-flash"
  FRONTEND_URL: "http://frontend-service"
