import React, { useState, useEffect, useRef } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { motion, useInView, useAnimation } from 'framer-motion';
import { FiBriefcase, FiMic, FiFileText, FiBarChart2, FiZap, FiMap, FiArrowRight, FiCheck, FiStar, FiUsers, FiAward, FiTrendingUp } from 'react-icons/fi';

/* ---------- animated counter ---------- */
function Counter({ end, suffix = '', duration = 2 }) {
  const [count, setCount] = useState(0);
  const ref = useRef(null);
  const inView = useInView(ref, { once: true });
  useEffect(() => {
    if (!inView) return;
    let start = 0;
    const step = end / (duration * 60);
    const timer = setInterval(() => {
      start += step;
      if (start >= end) { setCount(end); clearInterval(timer); }
      else setCount(Math.floor(start));
    }, 1000 / 60);
    return () => clearInterval(timer);
  }, [inView, end, duration]);
  return <span ref={ref}>{count.toLocaleString()}{suffix}</span>;
}

/* ---------- feature cards ---------- */
const features = [
  { icon: FiBriefcase, title: 'AI Mock Interviews', desc: 'Practice HR, Technical, Behavioral & Domain-specific interviews powered by Gemini AI.', color: 'from-violet-500 to-purple-600' },
  { icon: FiMic, title: 'Speech Analysis', desc: 'Get real-time feedback on filler words, speaking pace, confidence, grammar & tone.', color: 'from-cyan-500 to-blue-600' },
  { icon: FiFileText, title: 'Resume ATS Scorer', desc: 'Upload your PDF resume and get an instant ATS compatibility score with AI suggestions.', color: 'from-emerald-500 to-teal-600' },
  { icon: FiBarChart2, title: 'Real-time Feedback', desc: 'Instant analysis after every answer with scores, strengths, and improvement tips.', color: 'from-orange-500 to-amber-600' },
  { icon: FiTrendingUp, title: 'Progress Tracking', desc: 'Track your improvement over time with interactive charts and performance insights.', color: 'from-pink-500 to-rose-600' },
  { icon: FiMap, title: 'AI Career Roadmap', desc: 'Get a personalized career roadmap and action plan generated by AI for your target role.', color: 'from-indigo-500 to-violet-600' },
];

/* ---------- pricing tiers ---------- */
const plans = [
  {
    name: 'Free', price: 0, desc: 'Perfect to get started',
    features: ['3 Mock Interviews/month', '1 Resume Analysis', 'Basic Speech Metrics', 'Community Access'],
    cta: 'Get Started Free', highlighted: false,
  },
  {
    name: 'Pro', price: 29, desc: 'For serious job seekers',
    features: ['Unlimited Mock Interviews', 'Unlimited Resume Analyses', 'Advanced Speech AI', 'AI Career Roadmap', 'Priority Support', 'Downloadable Reports'],
    cta: 'Start Pro Trial', highlighted: true,
  },
  {
    name: 'Enterprise', price: 99, desc: 'For teams & organizations',
    features: ['Everything in Pro', 'Team Dashboard', 'Custom Interview Domains', 'API Access', 'Dedicated Support', 'Custom Branding'],
    cta: 'Contact Sales', highlighted: false,
  },
];

/* ---------- testimonials ---------- */
const testimonials = [
  { name: 'Priya Sharma', role: 'SDE at Google', text: 'InterviewAI helped me crack my FAANG interview in just 3 weeks! The speech analysis was a game-changer.', rating: 5, avatar: 'PS' },
  { name: 'James Carter', role: 'Product Manager at Meta', text: 'The AI-generated questions were incredibly relevant to my target role. My confidence score went from 58 to 91!', rating: 5, avatar: 'JC' },
  { name: 'Aisha Malik', role: 'Data Scientist at Amazon', text: 'The resume ATS scorer showed me exactly why I wasn\'t getting callbacks. Fixed it in one session!', rating: 5, avatar: 'AM' },
];

const steps = [
  { step: '01', title: 'Create Account', desc: 'Sign up free with email or Google in under 30 seconds.' },
  { step: '02', title: 'Choose Interview', desc: 'Select your domain, difficulty, and interview type.' },
  { step: '03', title: 'Practice with AI', desc: 'Answer AI-generated questions via voice with real-time transcription.' },
  { step: '04', title: 'Get Feedback', desc: 'Receive detailed scores, analysis, and your personalized roadmap.' },
];

export default function LandingPage() {
  const navigate = useNavigate();
  const [billingAnnual, setBillingAnnual] = useState(false);

  return (
    <div className="min-h-screen bg-[#0a0b14] text-white font-sans overflow-x-hidden">

      {/* ---- NAVBAR ---- */}
      <nav className="fixed top-0 left-0 right-0 z-50 bg-[#0a0b14]/80 backdrop-blur-xl border-b border-white/5">
        <div className="max-w-7xl mx-auto px-6 h-16 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-violet-500 to-cyan-500 flex items-center justify-center text-sm font-bold">AI</div>
            <span className="font-bold text-xl bg-gradient-to-r from-violet-400 to-cyan-400 bg-clip-text text-transparent">InterviewAI</span>
          </div>
          <div className="hidden md:flex items-center gap-8 text-sm text-slate-400">
            <a href="#features" className="hover:text-white transition-colors">Features</a>
            <a href="#how-it-works" className="hover:text-white transition-colors">How It Works</a>
            <a href="#pricing" className="hover:text-white transition-colors">Pricing</a>
            <a href="#testimonials" className="hover:text-white transition-colors">Reviews</a>
          </div>
          <div className="flex items-center gap-3">
            <Link to="/login" className="text-sm text-slate-300 hover:text-white transition-colors px-4 py-2">Log In</Link>
            <Link to="/register" className="text-sm bg-gradient-to-r from-violet-600 to-cyan-600 hover:from-violet-500 hover:to-cyan-500 text-white px-4 py-2 rounded-lg transition-all font-medium">
              Get Started Free
            </Link>
          </div>
        </div>
      </nav>

      {/* ---- HERO ---- */}
      <section className="pt-32 pb-20 px-6 relative overflow-hidden">
        {/* background glows */}
        <div className="absolute top-20 left-1/4 w-96 h-96 bg-violet-600/20 rounded-full blur-3xl pointer-events-none" />
        <div className="absolute top-40 right-1/4 w-80 h-80 bg-cyan-600/20 rounded-full blur-3xl pointer-events-none" />

        <div className="max-w-5xl mx-auto text-center relative z-10">
          <motion.div initial={{ opacity: 0, y: 30 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.6 }}>
            <span className="inline-flex items-center gap-2 bg-violet-500/10 border border-violet-500/30 text-violet-300 text-sm px-4 py-1.5 rounded-full mb-8">
              <FiZap size={14} /> AI-Powered Interview Coaching Platform
            </span>
          </motion.div>

          <motion.h1
            className="text-5xl md:text-7xl font-bold leading-tight mb-6"
            initial={{ opacity: 0, y: 30 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.6, delay: 0.1 }}
          >
            Master Your Interview.{' '}
            <span className="bg-gradient-to-r from-violet-400 via-cyan-400 to-emerald-400 bg-clip-text text-transparent">
              Land Your Dream Job.
            </span>
          </motion.h1>

          <motion.p
            className="text-xl text-slate-400 max-w-2xl mx-auto mb-10"
            initial={{ opacity: 0, y: 30 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.6, delay: 0.2 }}
          >
            Practice unlimited AI mock interviews, get real-time speech analysis, boost your resume ATS score, and track your improvement — all in one platform.
          </motion.p>

          <motion.div
            className="flex flex-col sm:flex-row gap-4 justify-center"
            initial={{ opacity: 0, y: 30 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.6, delay: 0.3 }}
          >
            <Link to="/register" className="flex items-center justify-center gap-2 bg-gradient-to-r from-violet-600 to-cyan-600 hover:from-violet-500 hover:to-cyan-500 text-white px-8 py-4 rounded-xl font-semibold text-lg transition-all hover:shadow-lg hover:shadow-violet-500/25 hover:-translate-y-0.5">
              Start Free — No Credit Card <FiArrowRight />
            </Link>
            <Link to="/login" className="flex items-center justify-center gap-2 border border-white/10 hover:border-white/30 text-white px-8 py-4 rounded-xl font-semibold text-lg transition-all hover:bg-white/5">
              Sign In
            </Link>
          </motion.div>

          {/* Hero stats */}
          <motion.div
            className="mt-16 grid grid-cols-2 md:grid-cols-4 gap-6"
            initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 0.5 }}
          >
            {[
              { val: 50000, suffix: '+', label: 'Users' },
              { val: 95, suffix: '%', label: 'Success Rate' },
              { val: 200, suffix: '+', label: 'Companies' },
              { val: 4.9, suffix: '★', label: 'Rating' },
            ].map((s) => (
              <div key={s.label} className="bg-white/5 border border-white/10 rounded-2xl p-4">
                <div className="text-3xl font-bold bg-gradient-to-r from-violet-400 to-cyan-400 bg-clip-text text-transparent">
                  <Counter end={s.val} suffix={s.suffix} />
                </div>
                <div className="text-slate-400 text-sm mt-1">{s.label}</div>
              </div>
            ))}
          </motion.div>
        </div>
      </section>

      {/* ---- FEATURES ---- */}
      <section id="features" className="py-24 px-6">
        <div className="max-w-7xl mx-auto">
          <div className="text-center mb-16">
            <h2 className="text-4xl font-bold mb-4">Everything You Need to <span className="bg-gradient-to-r from-violet-400 to-cyan-400 bg-clip-text text-transparent">Succeed</span></h2>
            <p className="text-slate-400 text-lg max-w-2xl mx-auto">A complete AI-powered platform to prepare you for every aspect of the interview process.</p>
          </div>
          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
            {features.map((f, i) => (
              <motion.div
                key={f.title}
                className="bg-white/5 border border-white/10 rounded-2xl p-6 hover:border-white/20 hover:bg-white/[0.07] transition-all group cursor-pointer"
                initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }}
                transition={{ delay: i * 0.1 }} viewport={{ once: true }}
              >
                <div className={`w-12 h-12 rounded-xl bg-gradient-to-br ${f.color} flex items-center justify-center mb-4 group-hover:scale-110 transition-transform`}>
                  <f.icon size={22} className="text-white" />
                </div>
                <h3 className="text-lg font-semibold mb-2">{f.title}</h3>
                <p className="text-slate-400 text-sm leading-relaxed">{f.desc}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* ---- HOW IT WORKS ---- */}
      <section id="how-it-works" className="py-24 px-6 bg-white/[0.02]">
        <div className="max-w-6xl mx-auto">
          <div className="text-center mb-16">
            <h2 className="text-4xl font-bold mb-4">How It <span className="bg-gradient-to-r from-violet-400 to-cyan-400 bg-clip-text text-transparent">Works</span></h2>
            <p className="text-slate-400 text-lg">Get interview-ready in 4 simple steps.</p>
          </div>
          <div className="grid md:grid-cols-4 gap-8">
            {steps.map((s, i) => (
              <motion.div key={s.step} className="text-center" initial={{ opacity: 0, y: 30 }} whileInView={{ opacity: 1, y: 0 }} transition={{ delay: i * 0.15 }} viewport={{ once: true }}>
                <div className="text-6xl font-black bg-gradient-to-br from-violet-500/30 to-cyan-500/30 bg-clip-text text-transparent mb-4">{s.step}</div>
                <h3 className="text-lg font-semibold mb-2">{s.title}</h3>
                <p className="text-slate-400 text-sm">{s.desc}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* ---- TESTIMONIALS ---- */}
      <section id="testimonials" className="py-24 px-6">
        <div className="max-w-6xl mx-auto">
          <div className="text-center mb-16">
            <h2 className="text-4xl font-bold mb-4">Loved by <span className="bg-gradient-to-r from-violet-400 to-cyan-400 bg-clip-text text-transparent">50,000+ Job Seekers</span></h2>
          </div>
          <div className="grid md:grid-cols-3 gap-6">
            {testimonials.map((t, i) => (
              <motion.div key={t.name} className="bg-white/5 border border-white/10 rounded-2xl p-6" initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} transition={{ delay: i * 0.1 }} viewport={{ once: true }}>
                <div className="flex gap-1 mb-4">{[...Array(t.rating)].map((_, j) => <FiStar key={j} className="text-amber-400 fill-amber-400" size={16} />)}</div>
                <p className="text-slate-300 text-sm leading-relaxed mb-6">"{t.text}"</p>
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 rounded-full bg-gradient-to-br from-violet-500 to-cyan-500 flex items-center justify-center text-sm font-bold">{t.avatar}</div>
                  <div>
                    <div className="font-semibold text-sm">{t.name}</div>
                    <div className="text-slate-400 text-xs">{t.role}</div>
                  </div>
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* ---- PRICING ---- */}
      <section id="pricing" className="py-24 px-6 bg-white/[0.02]">
        <div className="max-w-6xl mx-auto">
          <div className="text-center mb-12">
            <h2 className="text-4xl font-bold mb-4">Simple, <span className="bg-gradient-to-r from-violet-400 to-cyan-400 bg-clip-text text-transparent">Transparent Pricing</span></h2>
            <div className="flex items-center justify-center gap-3 mt-6">
              <span className={`text-sm ${!billingAnnual ? 'text-white' : 'text-slate-400'}`}>Monthly</span>
              <button onClick={() => setBillingAnnual(!billingAnnual)} className={`relative w-12 h-6 rounded-full transition-colors ${billingAnnual ? 'bg-violet-600' : 'bg-slate-700'}`}>
                <div className={`absolute top-1 w-4 h-4 bg-white rounded-full transition-all ${billingAnnual ? 'left-7' : 'left-1'}`} />
              </button>
              <span className={`text-sm ${billingAnnual ? 'text-white' : 'text-slate-400'}`}>Annual <span className="text-emerald-400">20% off</span></span>
            </div>
          </div>

          <div className="grid md:grid-cols-3 gap-6">
            {plans.map((p, i) => (
              <motion.div
                key={p.name}
                className={`rounded-2xl p-8 border ${p.highlighted ? 'bg-gradient-to-b from-violet-900/50 to-cyan-900/30 border-violet-500/50 relative' : 'bg-white/5 border-white/10'}`}
                initial={{ opacity: 0, y: 30 }} whileInView={{ opacity: 1, y: 0 }} transition={{ delay: i * 0.1 }} viewport={{ once: true }}
              >
                {p.highlighted && (
                  <div className="absolute -top-3 left-1/2 -translate-x-1/2 bg-gradient-to-r from-violet-600 to-cyan-600 text-xs font-semibold px-4 py-1 rounded-full">
                    Most Popular
                  </div>
                )}
                <h3 className="text-xl font-bold mb-1">{p.name}</h3>
                <p className="text-slate-400 text-sm mb-4">{p.desc}</p>
                <div className="mb-6">
                  <span className="text-4xl font-black">${billingAnnual ? Math.round(p.price * 0.8) : p.price}</span>
                  {p.price > 0 && <span className="text-slate-400 text-sm">/mo</span>}
                </div>
                <Link to="/register" className={`block text-center py-3 rounded-xl font-semibold text-sm mb-8 transition-all ${p.highlighted ? 'bg-gradient-to-r from-violet-600 to-cyan-600 hover:from-violet-500 hover:to-cyan-500 text-white' : 'border border-white/20 hover:border-white/40 hover:bg-white/5'}`}>
                  {p.cta}
                </Link>
                <ul className="space-y-3">
                  {p.features.map((f) => (
                    <li key={f} className="flex items-center gap-3 text-sm text-slate-300">
                      <FiCheck className="text-emerald-400 shrink-0" size={16} />
                      {f}
                    </li>
                  ))}
                </ul>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* ---- CTA ---- */}
      <section className="py-24 px-6">
        <div className="max-w-4xl mx-auto text-center">
          <motion.div className="bg-gradient-to-r from-violet-900/50 to-cyan-900/50 border border-white/10 rounded-3xl p-12" initial={{ opacity: 0, scale: 0.95 }} whileInView={{ opacity: 1, scale: 1 }} viewport={{ once: true }}>
            <h2 className="text-4xl font-bold mb-4">Ready to Land Your Dream Job?</h2>
            <p className="text-slate-300 text-lg mb-8">Join 50,000+ professionals who use InterviewAI to practice smarter and interview with confidence.</p>
            <Link to="/register" className="inline-flex items-center gap-2 bg-gradient-to-r from-violet-600 to-cyan-600 hover:from-violet-500 hover:to-cyan-500 text-white px-10 py-4 rounded-xl font-semibold text-lg transition-all hover:shadow-lg hover:shadow-violet-500/25">
              Start for Free Today <FiArrowRight />
            </Link>
          </motion.div>
        </div>
      </section>

      {/* ---- FOOTER ---- */}
      <footer className="border-t border-white/5 py-12 px-6">
        <div className="max-w-7xl mx-auto flex flex-col md:flex-row justify-between items-center gap-6">
          <div className="flex items-center gap-2">
            <div className="w-7 h-7 rounded-lg bg-gradient-to-br from-violet-500 to-cyan-500 flex items-center justify-center text-xs font-bold">AI</div>
            <span className="font-bold bg-gradient-to-r from-violet-400 to-cyan-400 bg-clip-text text-transparent">InterviewAI</span>
            <span className="text-slate-500 text-sm ml-2">© 2026 workforme.space</span>
          </div>
          <div className="flex gap-6 text-sm text-slate-500">
            <Link to="/pricing" className="hover:text-white transition-colors">Pricing</Link>
            <Link to="/contact" className="hover:text-white transition-colors">Contact</Link>
            <a href="#features" className="hover:text-white transition-colors">Features</a>
          </div>
        </div>
      </footer>
    </div>
  );
}
